version: '3.7'
#
#
services:
  gedge-db:
    image: 'linuxserver/mariadb:latest'
    container_name: gedge-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    volumes:
      - ./mariadb_data:/config
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - ./.env
    ports:
      - '12003:3306'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TIMEZONE
  gedge-phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: gedge-phpmyadmin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - '12004:80'
    links:
      - gedge-db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=gedge-db
      - PMA_PORT=3306
