version: "3"
services:
  # kraken_designer:
  #   image: devopsfaith/krakendesigner:latest
  #   ports:
  #     - "8787:80"
  gmc_api_gateway:
    image: devopsfaith/krakend:config-watcher
    container_name: gmc_api_gateway
    restart: unless-stopped
    volumes:
      - ./config:/etc/krakend
    environment:
      - KRAKEND_CONFIG=gm-center.json
      - FC_ENABLE=1
      - FC_SETTINGS=/etc/krakend/settings
      - FC_PARTIALS=/etc/krakend/partials
    ports:
      - "8080:8080"
